<?php
/*
<LICENSE>

This file is part of AGENCY.

AGENCY is Copyright (c) 2003-2017 by Ken Tanzer and Downtown Emergency
Service Center (DESC).

All rights reserved.

For more information about AGENCY, see http://agency-software.org/
For more information about DESC, see http://www.desc.org/.

AGENCY is free software: you can redistribute it and/or modify
it under the terms of version 3 of the GNU General Public License
as published by the Free Software Foundation.

AGENCY is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with AGENCY.  If not, see <http://www.gnu.org/licenses/>.

For additional information, see the README.copyright file that
should be included in this distribution.

</LICENSE>
*/

function send_email( $to,$subject,$message,$headers='' ) {
	// Use global var for sender of email
	// Set reply-to to recipient, to avoid emails going nowhere

	$headers .= 'From: ' . $GLOBALS['AG_EMAIL_SENDER']. "\r\n";
	$headers .= 'Reply-to: ' . $to. "\r\n";
	$headers .= "MIME-Version: 1.0\r\n";
	$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

	$footer = div(
		oline('This email was generated by AGENCY.')
		.oline('You cannot reply to this email.')
	,'','style="background: #EEEEFF; border-color: #000000; padding: 10;"');


/*
	$footer="\r\n\r\n"
			."+-----------------------------------------+\r\n"
			."|                                         |\r\n"
			."| This email was generated by AGENCY.     |\r\n"
			."| You cannot reply to this email.         |\r\n"
			."|                                         |\r\n"
			."+-----------------------------------------+\r\n";
*/
	return mail($to,$subject,'<html><body>'.$message .$footer.'</body></html>',$headers);
}


?>
