INSERT INTO tbl_l_gift_cash_form VALUES ('PCHK','Personal Check',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('FCHK','Foundation Check',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('CCHK','Corporate Check',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('OCHK','Organization Check',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('CASH','Cash',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('MONO','Money Order',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('CHECK_3P','Third Party Check',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('BANK','Bank Check',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('SECU','Stock/other Securities',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('INKI','In-kind (non-cash) donati',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('EFT','Electronic Funds Transfer',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('INDI','Indirect--through FFO',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('VISA','Credit Card--Visa',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_gift_cash_form VALUES ('MC','Credit Card--MasterCard',sys_user(),current_timestamp,sys_user(),current_timestamp);
