CREATE VIEW address AS SELECT 
	address_id,
	donor_id,
	address_date,
	address_date_end,
	address_obsolete_reason_code,
	address_type_code,
	exclude_from_mailing,
	name_prefix,
	name_first,
	name_middle,
	name_last,
	name_suffix,
	name_email,
	name2_prefix,
	name2_first,
	name2_middle,
	name2_last,
	name2_suffix,
	name2_email,
	organization,
	title,
	address1,
	address2,
	city,
	state_code,
	zipcode,
	salutation,
	country,
	phone_no,
	send_mail_code,
	address_comment,
	address_names(address_id) as address_names,
	address_mail(address_id) as address_mail,
	latitude_longitude,
	added_by,
	added_at,
	changed_by,
	changed_at,
	is_deleted,
	deleted_at,
	deleted_by,
	deleted_comment,
	sys_log
FROM tbl_address WHERE NOT is_deleted;
