<?php

/*
<LICENSE>

This file is part of AGENCY.

AGENCY is Copyright (c) 2003-2017 by Ken Tanzer and Downtown Emergency
Service Center (DESC).

All rights reserved.

For more information about AGENCY, see http://agency-software.org/
For more information about DESC, see http://www.desc.org/.

AGENCY is free software: you can redistribute it and/or modify
it under the terms of version 3 of the GNU General Public License
as published by the Free Software Foundation.

AGENCY is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with AGENCY.  If not, see <http://www.gnu.org/licenses/>.

For additional information, see the README.copyright file that
should be included in this distribution.

</LICENSE>
*/


$AG_SCRIPT_CONFIG_CLINICAL_REG = 
array(

	/************************************ HOST **************************************/
	'host_60' => array('title' => 'HOST 60 Registration',
				 'benefit_project' => 'HOST',
				 'objects' => array(
							  'clinical_reg_request' => array('group_field' => 'assessment_date',
												    'rec_fixed' => array('benefit_type_code' => '60',
																 'benefit_change_code' => 'INITIAL',
																 'funding_source_code' => 'KC'),
												    'hidden_fields' => array('previous_auth_id'),
												    'send_to_kc' => true),
							  AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
											     'update_existing' => true,
											     'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
											     ),
							  'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
											  'rec_fixed' => array('staff_assign_type_code' => 'CM_MH',
														     'staff_assign_date_end' => ''),
											  'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
											  'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																	'NULL:staff_assign_date_end' => '',
																	'!NULL:staff_id' => ''),
											  'close_previous' => 'on_change',
											  'send_to_kc' => true),
							  'referral_clinical' => array('many' => 3,
												 'group_on_fields' => array('referral_clinical_date'),
												 'rec_fixed' => array('referral_clinical_type_code' => 'INTO',
															    'referral_clinical_linkage_code' => 'NA'),
												 'passed_fields' => array('referral_clinical_code'),
												 'send_to_kc' => true,
												 'rec_hidden' => array('referral_clinical_type_code' => 'SCREENING',
															     'referral_clinical_linkage_code' => 'NA',
															     'referral_clinical_code' => '9998')
												 ),
							  'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
												 'send_to_kc' => true,
												 'rec_init_from_previous' => true),
							  'client_description' => array('group_on_fields' => array('client_description_date'),
												  'rec_init_from_previous' => true,
												  'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
							  'clinical_impression' => array('group_on_fields' => array('clinical_impression_date'),
												   'rec_init_from_previous' => true),
							  'homeless_status_clinical' => array('group_on_fields' => array('homeless_status_clinical_date'),
													  'rec_init_from_previous' => true),
							  'address' => array('group_on_fields' =>array('address_date'),
										   'passed_fields' => array('line_1','line_2'),
										   'rec_init_from_previous' => true,
										   'rec_fixed' => array('address_date_end' => '')),
							  'phone' => array('group_on_fields' => array('phone_date'),
										 'passed_fields' => array('number'),
										 'hidden_fields' => array('phone_date_end'),
										 'close_previous' => 'on_change',
										 'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
							  'residence_clinical' => array('send_to_kc' => true,
												  'rec_init_from_previous' => true),
							  'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
												   'many' => 6,
												   'passed_fields' => array('disability_clinical_code'),
												   'common_fields' => array('substance_abuse_clinical_code'),
												   'rec_init_from_previous' => true,
												   'send_to_kc' => true),
							  'medicaid' => array('group_on_fields' => array('medicaid_date'),
										    'send_to_kc' => false,
										    'rec_init_from_previous' => true)
							  )
				 ),
	'host_60_update' => array('title' => 'HOST 60 Update',
					  'benefit_project' => 'HOST',
					  'objects' => array('update' => array('type'=>'virtual',
											   'group_field' => 'update_date',
											   'def' => array('object' => 'update',
														'singular' => 'Update',
														'fields' => array('update_date' => array('data_type' => 'date_past',
																				     'default' => today(),
																				     'label_add' => 'Update Date',
																				     'label_format_add' => '$x',
																				     'value_add' => '$x',
																				     'value_format_add' => '$x'))
														)),
								   'clinical_reg' => array('type' => 'view',
												   'filter' => array('benefit_type_code'=>'60',
															   '!IN:kc_authorization_status_code' => array('CX'),
															   'NULL:clinical_reg_date_end'=>''),
												   'hidden_fields' => array('kc_exit_type_code','clinical_exit_reason_code')
												   ),
								   AG_MAIN_OBJECT_DB => array('send_to_kc' => 'on_change_only',
													'update_existing' => true,
													'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
													),
								   'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
												   'rec_fixed' => array('staff_assign_type_code' => 'CM_MH',
																'staff_assign_date_end' => ''),
												   'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
												   'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																		 'NULL:staff_assign_date_end' => '',
																		 '!NULL:staff_id' => ''),
												   'close_previous' => 'on_change',
												   'send_to_kc' => 'on_change_only'),
								   'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
													  'send_to_kc' => 'on_change_only',
													  'rec_init_from_previous' => true),
								   'client_description' => array('group_on_fields' => array('client_description_date'),
													   'rec_init_from_previous' => true,
													   'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
								   'clinical_impression' => array('group_on_fields' => array('clinical_impression_date'),
													    'rec_init_from_previous' => true),
								   'homeless_status_clinical' => array('group_on_fields' => array('homeless_status_clinical_date'),
														   'rec_init_from_previous' => true),
								   'address' => array('group_on_fields' =>array('address_date'),
											    'passed_fields' => array('line_1','line_2'),
											    'rec_init_from_previous' => true,
											    'rec_fixed' => array('address_date_end' => '')),
								   'phone' => array('group_on_fields' => array('phone_date'),
											  'passed_fields' => array('number'),
											  'hidden_fields' => array('phone_date_end'),
											  'close_previous' => 'on_change',
											  'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
								   'residence_clinical' => array('send_to_kc' => 'on_change_only',
													   'rec_init_from_previous' => true),
								   'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
													    'many' => 6,
													    'passed_fields' => array('disability_clinical_code'),
													    'common_fields' => array('substance_abuse_clinical_code'),
													    'rec_init_from_previous' => true,
													    'send_to_kc' => 'on_change_only'),
								   'medicaid' => array('group_on_fields' => array('medicaid_date'),
											     'send_to_kc' => false,
											     'rec_init_from_previous' => true)
								   )
					  ),
	'host_60_exit' => array('title' => 'HOST 60 Exit',
					'benefit_project' => 'HOST',
					'benefit_type_code' => '60',
					'objects' => array('clinical_reg' => array('group_field'  => 'clinical_reg_date_end',
												 'rec_fixed'    => array('kc_exit_type_code' => 'TERMINATE'),
												 'fixed_fields' => array('clinical_reg_date',
																 'benefit_type_code',
																 'funding_source_code',
																 'kc_authorization_id',
																 'current_case_rate',
																 'case_rate_reason_code',
																 'kc_exit_type_code',
																 'kc_authorization_status_code'),
												 'update_existing' => true,
												 'required_fields' => array('clinical_reg_date_end'),
												 'send_to_kc' => true
												 ),
								 AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
												    'update_existing' => true,
												    'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
												    ),
								 'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
												 'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
												 'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
												 'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																	     'NULL:staff_assign_date_end' => '',
																	     '!NULL:staff_id' => ''),
												 'send_to_kc' => false,
												 'close_previous' => 'on_change'),
								 'referral_clinical' => array('many' => 3,
													'group_on_fields' => array('referral_clinical_date'),
													'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
													'passed_fields' => array('referral_clinical_code','referral_clinical_linkage_code'),
													'send_to_kc' => true),
								 'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
													'rec_init_from_previous' => true,
													'send_to_kc' => true),
								 'client_description' => array('group_on_fields' => array('client_description_date'),
													 'rec_init_from_previous' => true,
													 'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
								 'clinical_impression' => array('group_on_fields' => array('clinical_impression_date'),
													  'rec_init_from_previous' => true),
								 'homeless_status_clinical' => array('group_on_fields' => array('homeless_status_clinical_date'),
														 'rec_init_from_previous' => true),
								 'address' => array('group_on_fields' =>array('address_date'),
											  'passed_fields' => array('line_1','line_2'),
											  'rec_init_from_previous' => true,
											  'rec_fixed' => array('address_date_end' => '')),
								 'phone' => array('group_on_fields' => array('phone_date'),
											'passed_fields' => array('number'),
											'hidden_fields' => array('phone_date_end'),
											'close_previous' => 'on_change',
											'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
								 'residence_clinical' => array('send_to_kc' => true,
													 'rec_init_from_previous' => true),
								 'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
													  'many' => 6,
													  'passed_fields' => array('disability_clinical_code'),
													  'common_fields' => array('substance_abuse_clinical_code'),
													  'rec_init_from_previous' => true,
													  'send_to_kc' => true),
								 'medicaid' => array('group_on_fields' => array('medicaid_date'),
											   'send_to_kc' => false,
											   'rec_init_from_previous' => true)
								 )
					),
	'host_61' => array('title' => 'HOST 61 Registration',
				 'benefit_project' => 'HOST',
			
				 'objects' => array(
							  'clinical_reg_request' => array('group_field' => 'assessment_date',
												    'rec_fixed' => array('benefit_type_code' => '61',
																 'benefit_change_code' => 'INITIAL',
																 'previous_auth_id' => '',
																 'funding_source_code' => 'KC'),
												    'send_to_kc' => true),
							  AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
											     'update_existing' => true,
											     'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
											     ),
							  'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
											  'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
											  'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
											  'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																	'NULL:staff_assign_date_end' => '',
																	'!NULL:staff_id' => ''),
											  'send_to_kc' => true,
											  'close_previous' => 'on_change'),
							  'referral_clinical' => array('many' => 3,
												 'group_on_fields' => array('referral_clinical_date'),
												 'rec_fixed' => array('referral_clinical_type_code' => 'INTO',
															    'referral_clinical_linkage_code' => 'NA'),
												 'passed_fields' => array('referral_clinical_code'),
												 'send_to_kc' => true,
												 'rec_hidden' => array('referral_clinical_type_code' => 'SCREENING',
															     'referral_clinical_linkage_code' => 'NA',
															     'referral_clinical_code' => '9998')
												 ),
							  'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
												 'send_to_kc' => true,
												 'rec_init_from_previous' => true),
							  'client_description' => array('group_on_fields' => array('client_description_date'),
												  'rec_init_from_previous' => true,
												  'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
							  'address' => array('group_on_fields' =>array('address_date'),
										   'passed_fields' => array('line_1','line_2'),
										   'rec_fixed' => array('address_date_end' => ''),
										   'rec_init_from_previous' => true),
							  'phone' => array('group_on_fields' => array('phone_date'),
										 'passed_fields' => array('number'),
										 'hidden_fields' => array('phone_date_end'),
										 'close_previous' => 'on_change',
										 'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
							  'residence_clinical' => array('send_to_kc' => true,
												  'rec_init_from_previous' => true),
							  'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
												   'many' => 6,
												   'passed_fields' => array('disability_clinical_code'),
												   'common_fields' => array('substance_abuse_clinical_code'),
												   'rec_init_from_previous' => true,
												   'send_to_kc' => true),
							  'veteran_status_clinical' => array('group_on_fields' => array('veteran_status_clinical_date'),
													 'rec_init_from_previous' => true),
							  'medicaid' => array('group_on_fields' => array('medicaid_date'),
										    'send_to_kc' => true,
										    'rec_init_from_previous' => true),
							  'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
												   'send_to_kc' => true,
												   'rec_init_from_previous' => true),
							  'diagnosis' => array('many' => 5,
										     'group_on_fields' => array('diagnosis_date'),
										     'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
										     'rec_init_from_previous' => true,
										     'send_to_kc' => true)
							  )
				 ),

	'host_61_update' => array('title' => 'HOST 61 Update',
					  'benefit_project' => 'HOST',
					  'objects' => array('update' => array('type'=>'virtual',
											   'group_field' => 'update_date',
											   'def' => array('object' => 'update',
														'singular' => 'Update',
														'fields' => array('update_date' => array('data_type' => 'date_past',
																				     'default' => today(),
																				     'label_add' => 'Update Date',
																				     'label_format_add' => '$x',
																				     'value_add' => '$x',
																				     'value_format_add' => '$x'))
														)),
								   'clinical_reg' => array('type' => 'view',
												   'filter' => array('benefit_type_code'=>'61',
															   '!IN:kc_authorization_status_code' => array('CX'),
															   'NULL:clinical_reg_date_end'=>''),
												   'hidden_fields' => array('kc_exit_type_code','clinical_exit_reason_code')
												   ),
								   AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
													'update_existing' => true,
													'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
													),
								   'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
												   'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
												   'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
												   'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																		 'NULL:staff_assign_date_end' => '',
																		 '!NULL:staff_id' => ''),
												   'send_to_kc' => 'on_change_only',
												   'close_previous' => 'on_change'),
								   'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
													  'rec_init_from_previous' => true,
													  'send_to_kc' => 'on_change_only'),
								   'client_description' => array('group_on_fields' => array('client_description_date'),
													   'rec_init_from_previous' => true,
													   'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
								   'address' => array('group_on_fields' =>array('address_date'),
											    'passed_fields' => array('line_1','line_2'),
											    'rec_init_from_previous' => true,
											    'rec_fixed' => array('address_date_end' => '')),
								   'phone' => array('group_on_fields' => array('phone_date'),
											  'passed_fields' => array('number'),
											  'hidden_fields' => array('phone_date_end'),
											  'close_previous' => 'on_change',
											  'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
								   'residence_clinical' => array('send_to_kc' => 'on_change_only',
													   'rec_init_from_previous' => true),
								   'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
													    'many' => 6,
													    'passed_fields' => array('disability_clinical_code'),
													    'common_fields' => array('substance_abuse_clinical_code'),
													    'rec_init_from_previous' => true,
													    'send_to_kc' => 'on_change_only'),
								   'veteran_status_clinical' => array('group_on_fields' => array('veteran_status_clinical_date'),
														  'rec_init_from_previous' => true),
								   'medicaid' => array('group_on_fields' => array('medicaid_date'),
											     'rec_init_from_previous' => true,
											     'send_to_kc' => 'on_change_only'),
								   'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
													    'rec_init_from_previous' => true,
													    'send_to_kc' => 'on_change_only'),
								   'diagnosis' => array('many' => 5,
												'group_on_fields' => array('diagnosis_date'),
												'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
												'rec_init_from_previous' => true,
												'send_to_kc' => 'on_change_only')
								   )
					  ),
	'host_61_exit' => array('title' => 'HOST 61 Exit',
					'benefit_project' => 'HOST',
					'benefit_type_code' => '61', 
					'objects' => array('clinical_reg' => array('group_field'  => 'clinical_reg_date_end',
												   'rec_fixed'    => array('kc_exit_type_code' => 'TERMINATE'),
												   'fixed_fields' => array('clinical_reg_date',
																   'benefit_type_code',
																   'funding_source_code',
																   'kc_authorization_id',
																   'current_case_rate',
																   'case_rate_reason_code',
																   'kc_exit_type_code',
																   'kc_authorization_status_code'),
												   'update_existing' => true,
												   'required_fields' => array('clinical_reg_date_end'),
												   'send_to_kc' => true
												   ),
								   AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
													'update_existing' => true,
													'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
													),
								   'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
												   'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
												   'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
												   'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																		 'NULL:staff_assign_date_end' => '',
																		 '!NULL:staff_id' => ''),
												   'send_to_kc' => false,
												   'close_previous' => 'on_change'),
								   'referral_clinical' => array('many' => 3,
													  'group_on_fields' => array('referral_clinical_date'),
													  'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
													  'passed_fields' => array('referral_clinical_code','referral_clinical_linkage_code'),
													  'send_to_kc' => true),
								   'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
													  'rec_init_from_previous' => true,
													  'send_to_kc' => 'on_change_only'),
								   'client_description' => array('group_on_fields' => array('client_description_date'),
													   'rec_init_from_previous' => true,
													   'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
								   'address' => array('group_on_fields' =>array('address_date'),
											    'passed_fields' => array('line_1','line_2'),
											    'rec_init_from_previous' => true,
											    'rec_fixed' => array('address_date_end' => '')),
								   'phone' => array('group_on_fields' => array('phone_date'),
											  'passed_fields' => array('number'),
											  'hidden_fields' => array('phone_date_end'),
											  'close_previous' => 'on_change',
											  'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
								   'residence_clinical' => array('send_to_kc' => 'on_change_only',
													   'rec_init_from_previous' => true),
								   'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
													    'many' => 6,
													    'passed_fields' => array('disability_clinical_code'),
													    'common_fields' => array('substance_abuse_clinical_code'),
													    'rec_init_from_previous' => true,
													    'send_to_kc' => 'on_change_only'),
								   'veteran_status_clinical' => array('group_on_fields' => array('veteran_status_clinical_date'),
														  'rec_init_from_previous' => true),
								   'medicaid' => array('group_on_fields' => array('medicaid_date'),
											     'rec_init_from_previous' => true,
											     'send_to_kc' => 'on_change_only'),
								   'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
													    'rec_init_from_previous' => true,
													    'send_to_kc' => 'on_change_only'),
								   'diagnosis' => array('many' => 5,
												'group_on_fields' => array('diagnosis_date'),
												'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
												'rec_init_from_previous' => true,
												'send_to_kc' => true)
								   )
					  ),

	/************************************ SAGE **************************************/

	'sage' => array('title' => 'SAGE Registration',
			    'benefit_project' => 'SAGE',
			    'objects' => array(
						     'clinical_reg_request' => array('group_field' => 'assessment_date',
												 //'rec_fixed' => array('benefit_type_code' => '61',
												 //'benefit_change_code' => 'INITIAL',
												 //'previous_auth_id' => ''),
												 'send_to_kc' => true),
						     AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
											  'update_existing' => true,
											  'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
											  ),
						     'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
										     'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
										     'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
										     'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																   'NULL:staff_assign_date_end' => '',
																   '!NULL:staff_id' => ''),
										     'send_to_kc' => true,
										     'close_previous' => 'on_change'),
						     'referral_clinical' => array('many' => 3,
											    'group_on_fields' => array('referral_clinical_date'),
											    'rec_fixed' => array('referral_clinical_type_code' => 'INTO',
															 'referral_clinical_linkage_code' => 'NA'),
											    'passed_fields' => array('referral_clinical_code'),
											    'send_to_kc' => true,
											    'rec_hidden' => array('referral_clinical_type_code' => 'SCREENING',
															  'referral_clinical_linkage_code' => 'NA',
															  'referral_clinical_code' => '9998')
											    ),
						     'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
											    'send_to_kc' => true,
											    'rec_init_from_previous' => true),
						     'client_description' => array('group_on_fields' => array('client_description_date'),
											     'rec_init_from_previous' => true,
											     'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
						     'address' => array('group_on_fields' =>array('address_date'),
										'rec_init_from_previous' => true,
										'passed_fields' => array('line_1','line_2'),
										'rec_fixed' => array('address_date_end' => '')),
						     'phone' => array('group_on_fields' => array('phone_date'),
									    'passed_fields' => array('number'),
									    'hidden_fields' => array('phone_date_end'),
									    'close_previous' => 'on_change',
									    'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
						     'residence_clinical' => array('send_to_kc' => true,
											     'rec_init_from_previous' => true),
						     'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
												'many' => 6,
												'passed_fields' => array('disability_clinical_code'),
												'common_fields' => array('substance_abuse_clinical_code'),
												'rec_init_from_previous' => true,
												'send_to_kc' => true),
						     'veteran_status_clinical' => array('group_on_fields' => array('veteran_status_clinical_date'),
												    'rec_init_from_previous' => true),
						     'medicaid' => array('group_on_fields' => array('medicaid_date'),
										 'rec_init_from_previous' => true,
										 'send_to_kc' => true),
						     'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
												'rec_init_from_previous' => true,
												'send_to_kc' => true),
						     'clinical_condition_at_assessment' => array('many' => 2,
														 'group_on_fields' => array('clinical_condition_at_assessment_date'),
														 'passed_fields' => array('clinical_condition_at_assessment_code'),
														 'rec_init_from_previous' => true,
														 'send_to_kc' => true),
						     'pss' => array('group_on_fields' => array('pss_date'),
									  'rec_init_from_previous' => true,
									  'send_to_kc' => true),
						     'diagnosis' => array('many' => 5,
										  'group_on_fields' => array('diagnosis_date'),
										  'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
										  'rec_init_from_previous' => true,
										  'send_to_kc' => true)
						     
						     )
			    ),
	'sage_cob' => array('title' => 'SAGE Continuation of Benefit',
				  'benefit_project' => 'SAGE',
				  'objects' => array(
							   'clinical_reg_request' => array('group_field' => 'assessment_date',
												     'rec_fixed' => array('benefit_change_code' => 'COB',
																  'previous_auth_id' => '', //this gets filled in
																  'funding_source_code' => ''
																  ),
												     'send_to_kc' => true),
							   AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
												'update_existing' => true,
												'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
												),
							  'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
											  'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
											  'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
											  'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																	'NULL:staff_assign_date_end' => '',
																	'!NULL:staff_id' => ''),
											  'send_to_kc' => true,
											  'close_previous' => 'on_change'),
							   'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
												  'send_to_kc' => true,
												  'rec_init_from_previous' => true),
							   'client_description' => array('group_on_fields' => array('client_description_date'),
												   'rec_init_from_previous' => true,
												   'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
							   'address' => array('group_on_fields' =>array('address_date'),
										    'rec_init_from_previous' => true,
										    'passed_fields' => array('line_1','line_2'),
										    'rec_fixed' => array('address_date_end' => '')),
							   'phone' => array('group_on_fields' => array('phone_date'),
										  'passed_fields' => array('number'),
										  'hidden_fields' => array('phone_date_end'),
										  'close_previous' => 'on_change',
										  'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
							   'residence_clinical' => array('send_to_kc' => true,
												   'rec_init_from_previous' => true),
							   'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
												    'many' => 6,
												    'passed_fields' => array('disability_clinical_code'),
												    'common_fields' => array('substance_abuse_clinical_code'),
												    'rec_init_from_previous' => true,
												    'send_to_kc' => true),
							   'veteran_status_clinical' => array('group_on_fields' => array('veteran_status_clinical_date'),
													  'rec_init_from_previous' => true),
							   'medicaid' => array('group_on_fields' => array('medicaid_date'),
										     'rec_init_from_previous' => true,
										     'send_to_kc' => true),
							   'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
												    'rec_init_from_previous' => true,
												    'send_to_kc' => true),
							   'clinical_condition_at_assessment' => array('many' => 2,
														     'group_on_fields' => array('clinical_condition_at_assessment_date'),
														     'passed_fields' => array('clinical_condition_at_assessment_code'),
														     'rec_init_from_previous' => true,
														     'send_to_kc' => true),
							   'pss' => array('group_on_fields' => array('pss_date'),
										'rec_init_from_previous' => true,
										'send_to_kc' => true),
							   'diagnosis' => array('many' => 5,
											'group_on_fields' => array('diagnosis_date'),
											'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
											'rec_init_from_previous' => true,
											'send_to_kc' => true)
							   
							   )
				  ),
	'sage_update' => array('title' => 'SAGE Update',
				     'benefit_project' => 'SAGE',
				     'objects' => array('update' => array('type'=>'virtual',
											'group_field' => 'update_date',
											'def' => array('object' => 'update',
													   'singular' => 'Update',
													   'fields' => array('update_date' => array('data_type' => 'date_past',
																				  'default' => today(),
																				  'label_add' => 'Update Date',
																				  'label_format_add' => '$x',
																				  'value_add' => '$x',
																				  'value_format_add' => '$x'))
													   )),
								'clinical_reg' => array('type' => 'view',
												'filter' => array('tier_program(benefit_type_code)'=>'SAGE',
															'!IN:kc_authorization_status_code' => array('CX'),
															'FIELD>=:clinical_reg_date_end'=>'CURRENT_DATE'),
												'hidden_fields' => array('kc_exit_type_code','clinical_exit_reason_code')
												),
								AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
												   'update_existing' => true,
												   'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
												   ),
								'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
												'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
												'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
												'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																	    'NULL:staff_assign_date_end' => '',
																	    '!NULL:staff_id' => ''),
												'send_to_kc' => 'on_change_only',
												'close_previous' => 'on_change'),
								'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
												     'send_to_kc' => 'on_change_only',
												     'rec_init_from_previous' => true),
								'client_description' => array('group_on_fields' => array('client_description_date'),
													'rec_init_from_previous' => true,
													'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
								'address' => array('group_on_fields' =>array('address_date'),
											 'rec_init_from_previous' => true,
											 'passed_fields' => array('line_1','line_2'),
											 'rec_fixed' => array('address_date_end' => '')),
								'phone' => array('group_on_fields' => array('phone_date'),
										     'passed_fields' => array('number'),
										     'hidden_fields' => array('phone_date_end'),
										     'close_previous' => 'on_change',
										     'rec_init_from_previous' => array('NULL:phone_date_end' => '')),
								'residence_clinical' => array('send_to_kc' => 'on_change_only',
													'rec_init_from_previous' => true),
								'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
													 'many' => 6,
													 'passed_fields' => array('disability_clinical_code'),
													 'common_fields' => array('substance_abuse_clinical_code'),
													 'rec_init_from_previous' => true,
													 'send_to_kc' => 'on_change_only'),
								'veteran_status_clinical' => array('group_on_fields' => array('veteran_status_clinical_date'),
													     'rec_init_from_previous' => true),
								'medicaid' => array('group_on_fields' => array('medicaid_date'),
											  'rec_init_from_previous' => true,
											  'send_to_kc' => 'on_change_only'),
								'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
													 'rec_init_from_previous' => true,
													 'send_to_kc' => 'on_change_only'),
								'clinical_condition_at_assessment' => array('many' => 2,
															  'group_on_fields' => array('clinical_condition_at_assessment_date'),
															  'passed_fields' => array('clinical_condition_at_assessment_code'),
															  'rec_init_from_previous' => true,
															  'send_to_kc' => 'on_change_only'),
								'pss' => array('group_on_fields' => array('pss_date'),
										   'rec_init_from_previous' => true,
										   'send_to_kc' => 'on_change_only'),
								'diagnosis' => array('many' => 5,
											   'group_on_fields' => array('diagnosis_date'),
											   'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
											   'rec_init_from_previous' => true,
											   'send_to_kc' => 'on_change_only')
						     
								)
				     ),
	'sage_exit' => array('title' => 'SAGE Exit',
				   'benefit_project' => 'SAGE',
				   'objects' => array('clinical_reg' => array('group_field'  => 'clinical_reg_date_end',
											    'fixed_fields' => array('clinical_reg_date',
															    'benefit_type_code',
															    'funding_source_code',
															    'kc_authorization_id',
															    'current_case_rate',
															    'case_rate_reason_code',
															    'kc_authorization_status_code'),
											    'update_existing' => true,
											    'required_fields' => array('clinical_reg_date_end'),
											    'send_to_kc' => true
											    ),
							    AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
												 'update_existing' => true,
												 'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
												 ),
							    'staff_assign' => array('group_on_fields' => array('staff_assign_date'),
											    'rec_fixed' => array('staff_assign_type_code' => 'CM_MH'),
											    'hidden_fields' => array('staff_assign_date_end','send_alert','comment','name_last','name_first','agency_code','phone_1','phone_2','staff_id_name','contact_information'),
											    'rec_init_from_previous' => array('staff_assign_type_code' => 'CM_MH',
																	  'NULL:staff_assign_date_end' => '',
																	  '!NULL:staff_id' => ''),
											    'send_to_kc' => false,
											    'close_previous' => 'on_change'),
							    'referral_clinical' => array('many' => 3,
												   'group_on_fields' => array('referral_clinical_date'),
												   'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
												   'passed_fields' => array('referral_clinical_code','referral_clinical_linkage_code'),
												   'send_to_kc' => true),
							    'clinical_priority' => array('group_on_fields' => array('clinical_priority_date'),
												   'rec_init_from_previous' => true,
												   'send_to_kc' => true),
							    'client_description' => array('group_on_fields' => array('client_description_date'),
												    'rec_init_from_previous' => true,
												    'passed_fields' => array('height_ft','weight_lbs','hair','eyes','hygiene','clothing','other_features')),
							    'address' => array('group_on_fields' =>array('address_date'),
										     'rec_init_from_previous' => true,
										     'passed_fields' => array('line_1','line_2'),
										     'rec_fixed' => array('address_date_end' => '')),
							    'phone' => array('group_on_fields' => array('phone_date'),
										   'passed_fields' => array('number'),
										   'hidden_fields' => array('phone_date_end'),
										   'close_previous' => 'on_change',
										   'rec_init_from_previous' => array('NULL:phone_date_end'=>'')),
							    'residence_clinical' => array('send_to_kc' => true,
												    'rec_init_from_previous' => true),
							    'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
												     'many' => 6,
												     'passed_fields' => array('disability_clinical_code'),
												     'common_fields' => array('substance_abuse_clinical_code'),
												     'rec_init_from_previous' => true,
												     'send_to_kc' => true),
							    'veteran_status_clinical' => array('group_on_fields' => array('veteran_status_clinical_date'),
													   'rec_init_from_previous' => true),
							    'medicaid' => array('group_on_fields' => array('medicaid_date'),
											'rec_init_from_previous' => true,
											'send_to_kc' => true),
							    'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
												     'rec_init_from_previous' => true,
												     'send_to_kc' => true),
							    'clinical_condition_at_assessment' => array('many' => 2,
															'group_on_fields' => array('clinical_condition_at_assessment_date'),
															'passed_fields' => array('clinical_condition_at_assessment_code'),
															'send_to_kc' => true),
							    'pss' => array('group_on_fields' => array('pss_date'),
										 'rec_init_from_previous' => true,
										 'send_to_kc' => true),
							    'diagnosis' => array('many' => 5,
											 'group_on_fields' => array('diagnosis_date'),
											 'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
											 'rec_init_from_previous' => true,
											 'send_to_kc' => true)
						     
							    )
				   ),

	/********************************** PACT **************************************/

	'pact_57' => array('title' => 'PACT Engagement Registration',
					   'benefit_project' => 'PACT',
					   'objects' => array('clinical_reg_request' => array('group_field' => 'assessment_date',
														'rec_fixed' => array('benefit_type_code' => '57',
																	   'benefit_change_code' => 'INITIAL',
																	   'previous_auth_id' => '',
																	   'funding_source_code' => 'KC'),
														'send_to_kc' => true
														),
								    AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
													 'update_existing' => true,
													 'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
													 ),
								    'diagnosis' => array('many' => 5,
												 'group_on_fields' => array('diagnosis_date'),
												 'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
												 'rec_init_from_previous' => true,
												 'send_to_kc' => true)
								    )
					   ),

	'pact_57_update' => array('title' => 'PACT Engagement Update',
					  'benefit_project' => 'PACT',
					  'objects' => array('update' => array('type'=>'virtual',
											   'group_field'  => 'update_date',
											   
											   
											   'def' => array('object' => 'update',
												    'singular' => 'Update',
												    'fields' => array('update_date' => array('data_type' => 'date_past',
																			   'default' => today(),
																			   'label_add' => 'Update Date',
																			   'label_format_add' => '$x',
																			   'value_add' => '$x',
																			   'value_format_add' => '$x'))
												    )
													     ),


								   'clinical_reg' => array('type' => 'view',
												   'filter' => array('benefit_type_code'=>'57',
															   '!IN:kc_authorization_status_code' => array('CX'),
															   'NULL:clinical_reg_date_end'=>''
															   ),
												   'hidden_fields' => array('kc_exit_type_code','clinical_exit_reason_code')
												   ),

								   AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
													'update_existing' => true,
													'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
													),
								   
								   /*									   'referral_clinical' => array('many' => 3,
								    'group_on_fields' => array('referral_clinical_date'),
								    'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
								    'passed_fields' => array('referral_clinical_code',
								    'referral_clinical_linkage_code'),
								    'send_to_kc' => true),*/
								   
								   'diagnosis' => array('many' => 5,
												'group_on_fields' => array('diagnosis_date'),
												'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
												'rec_init_from_previous' => true,
												'send_to_kc' => true)
								   
									   )
						    ),

	'pact_57_exit' => array('title' => 'PACT Engagement Exit',
					'benefit_project' => 'PACT',
					'benefit_type_code' => '57',	
					'objects' => array('clinical_reg' => array('group_field'  => 'clinical_reg_date_end',
												 /*
												  // Commenting these fixed exits out.  People entering exits need to proceed with caution!
												  // See bug 23096
												  'rec_fixed'    => array(
												  'clinical_exit_reason_code' => 'NCRATE',
												  'kc_exit_type_code' => 'TERMINATE'),
												 */
												 'fixed_fields' => array('clinical_reg_date',
																 'benefit_type_code',
																 'funding_source_code',
																 'kc_authorization_id',
																 'current_case_rate',
																 'case_rate_reason_code',
																 'kc_exit_type_code',
																 'kc_authorization_status_code'),
													   'update_existing' => true,
												 'required_fields' => array('clinical_reg_date_end'),
												 'send_to_kc' => true
												 ),
								 AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
												    'update_existing' => true,
												    'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
												    ),
								 'referral_clinical' => array('many' => 3,
														  'group_on_fields' => array('referral_clinical_date'),
														  'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
														  'passed_fields' => array('referral_clinical_code',
																		   'referral_clinical_linkage_code'),
														  'send_to_kc' => true),

									   'diagnosis' => array('many' => 5,
													'group_on_fields' => array('diagnosis_date'),
													'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
													'rec_init_from_previous' => true,
													'send_to_kc' => true)
									   
									   )
						  ),

	'pact_58' => array('title' => 'PACT Enrollment Registration',
					   'benefit_project' => 'PACT',
					   'objects' => array('clinical_reg_request' => array('group_field' => 'assessment_date',
														'rec_fixed' => array('benefit_type_code' => '58',
																	   'benefit_change_code' => 'INITIAL',
																	   'previous_auth_id' => '',
																	   'funding_source_code' => 'KC'),
														'send_to_kc' => true
														),
								    AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
													 'update_existing' => true,
													 'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
													 ),
								    'diagnosis' => array('many' => 5,
												 'group_on_fields' => array('diagnosis_date'),
												 'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
												 'rec_init_from_previous' => true,
												 'send_to_kc' => true),
								    'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
													     'many' => 6,
													     'passed_fields' => array('disability_clinical_code'),
													     'common_fields' => array('substance_abuse_clinical_code'),
													     'rec_init_from_previous' => true,
													     'send_to_kc' => true),
								    'referral_clinical' => array('many' => 3,
													   'group_on_fields' => array('referral_clinical_date'),
													   'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
													   'passed_fields' => array('referral_clinical_code',
																	    'referral_clinical_linkage_code'),
													   'send_to_kc' => true),
								    'medicaid' => array('group_on_fields' => array('medicaid_date'),
												'rec_init_from_previous' => true,
												'send_to_kc' => true),
								    'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
													     'rec_init_from_previous' => true,
													     'send_to_kc' => true),
								    'residence_clinical' => array('send_to_kc' => true,
													    'rec_init_from_previous' => true)
								    )
					   ),

	'pact_58_update' => array('title' => 'PACT Enrollment Update',
						  'benefit_project' => 'PACT',

					    'objects' => array('update' => array('type'=>'virtual',
												     'group_field'  => 'update_date',

						  
										 'def' => array('object' => 'update',
												    'singular' => 'Update',
												    'fields' => array('update_date' => array('data_type' => 'date_past',
																			   'default' => today(),
																			   'label_add' => 'Update Date',
																			   'label_format_add' => '$x',
																			   'value_add' => '$x',
																			   'value_format_add' => '$x'))
												    )
													     ),


								            'clinical_reg' => array('type' => 'view',
												   'filter' => array('benefit_type_code'=>'58',
															      '!IN:kc_authorization_status_code' => array('CX'),
															   'NULL:clinical_reg_date_end'=>''
															   ),
													     'hidden_fields' => array('kc_exit_type_code','clinical_exit_reason_code')
													     ),

						  													   
									   AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
														'update_existing' => true,
														'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
														),
								     /* 'referral_clinical' => array('many' => 3,
														  'group_on_fields' => array('referral_clinical_date'),
														  'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
														  'passed_fields' => array('referral_clinical_code',
																		   'referral_clinical_linkage_code'),
																		   'send_to_kc' => true), */

									   'diagnosis' => array('many' => 5,
													'group_on_fields' => array('diagnosis_date'),
													'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
													'rec_init_from_previous' => true,
													'send_to_kc' => true),
									   'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
														    'many' => 6,
														    'passed_fields' => array('disability_clinical_code'),
														    'common_fields' => array('substance_abuse_clinical_code'),
														    'rec_init_from_previous' => true,
														    'send_to_kc' => true),
									   'medicaid' => array('group_on_fields' => array('medicaid_date'),
												     'rec_init_from_previous' => true,
												     'send_to_kc' => true),
									   'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
														    'rec_init_from_previous' => true,
														    'send_to_kc' => true),
									   'residence_clinical' => array('send_to_kc' => true,
														   'rec_init_from_previous' => true)
									   
									   )
						    ),

	'pact_58_exit' => array('title' => 'PACT Enrollment Exit',
					'benefit_project' => 'PACT',
					'benefit_type_code' => '58',
					'objects' => array('clinical_reg' => array('group_field'  => 'clinical_reg_date_end',
												 'rec_fixed'    => array('clinical_exit_reason_code' => 'NCRATE',
																	   'kc_exit_type_code' => 'TERMINATE'),
													   'fixed_fields' => array('clinical_reg_date',
																	   'benefit_type_code',
																	   'funding_source_code',
																	   'kc_authorization_id',
																	   'current_case_rate',
																	   'case_rate_reason_code',
																	   'kc_exit_type_code',
																	   'kc_authorization_status_code'),
													   'update_existing' => true,
													   'required_fields' => array('clinical_reg_date_end'),
													   'send_to_kc' => true
													   ),
									   AG_MAIN_OBJECT_DB => array('send_to_kc' => true,
														'update_existing' => true,
														'hidden_fields' => array('veteran_status_code','spc_id','is_protected_id','resident_id','name_full','name_full_alias','issue_no','last_photo_at','comments','med_issues','medications','med_allergies')
														),
									   'referral_clinical' => array('many' => 3,
														  'group_on_fields' => array('referral_clinical_date'),
														  'rec_fixed' => array('referral_clinical_type_code' => 'TO'),
														  'passed_fields' => array('referral_clinical_code',
																		   'referral_clinical_linkage_code'),
														  'send_to_kc' => true),

									   'diagnosis' => array('many' => 5,
													'group_on_fields' => array('diagnosis_date'),
													'passed_fields' => array('diagnosis_code','diagnosis_axis_code','gaf_score'),
													'rec_init_from_previous' => true,
													'send_to_kc' => true),
									   'disability_clinical' => array('group_on_fields' => array('disability_clinical_date'),
														    'many' => 6,
														    'passed_fields' => array('disability_clinical_code'),
														    'common_fields' => array('substance_abuse_clinical_code'),
														    'rec_init_from_previous' => true,
														    'send_to_kc' => true),
									   'medicaid' => array('group_on_fields' => array('medicaid_date'),
												     'rec_init_from_previous' => true,
												     'send_to_kc' => true),
									   'activity_evaluation' => array('group_on_fields' => array('activity_evaluation_date'),
														    'rec_init_from_previous' => true,
														    'send_to_kc' => true),
									   'residence_clinical' => array('send_to_kc' => true,
														   'rec_init_from_previous' => true)
									   
									   )
						  )

	);

	

?>
