CREATE TABLE tbl_config_email (
	config_email_id		SERIAL PRIMARY KEY,
	email_sender		VARCHAR,
	template_alert		TEXT,
	template_password_reset	TEXT,
	comment				TEXT,
	--system fields
	added_by                        INTEGER NOT NULL REFERENCES tbl_staff (staff_id),
	added_at                        TIMESTAMP(0)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
	changed_by                      INTEGER NOT NULL  REFERENCES tbl_staff (staff_id),
	changed_at                      TIMESTAMP(0)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_deleted                      BOOLEAN NOT NULL DEFAULT FALSE,
	deleted_at                      TIMESTAMP(0) CHECK ((NOT is_deleted AND deleted_at IS NULL) OR (is_deleted AND deleted_at IS NOT NULL)),
	deleted_by                      INTEGER REFERENCES tbl_staff(staff_id)
		CHECK ((NOT is_deleted AND deleted_by IS NULL) OR (is_deleted AND deleted_by IS NOT NULL)),
	deleted_comment         TEXT,
	sys_log                 TEXT
);

CREATE VIEW config_email AS (SELECT * FROM tbl_config_email WHERE NOT is_deleted);

INSERT INTO tbl_config_email (added_by,changed_by,sys_log,email_sender,template_alert,template_password_reset) VALUES  (sys_user(),sys_user(),'Adding initial config record','AGENCY Notifier <noreply@xxx.org>',
'<html><body style="background-color: #DDDDFF; padding-top: 10px;">
<div style="background-color: #EEEEFF; width:50%; border: solid black 2px; padding: 25px; padding-top: 10px; padding-bottom: 10px; border-radius: 8px; margin-left: 10px; margin-top: 10px;">
<span><a href="http://agency-software.org/" target="_blank"><img src="http://agency-software.org/agency_logo_medium.png"/></a></span>
<span style="font-size: 150%; font-weight: bold; vertical-align: middle; "><a href="$alert_url">$label</a></span>

<h1>You have received an <a href="$alert_url">AGENCY alert</a></h1>

You have received this email because your AGENCY user options are set to send an email whenever you receive a AGENCY alert. If you prefer not to receive emails about your alerts, you can <a href="$settings_url">change your settings</a>.
</div>
<br /><br />

<div style="margin-left:10px; margin-bottom: 10px; padding-bottom: 10px; ">This email was generated by <a href="http://agency-software.org/" target="_blank">AGENCY Software</a>.<br />
You cannot reply to this email.
</div>
</body></html>',

'<html><body style="background-color: #DDDDFF; padding-top: 10px;">
<div style="background-color: #EEEEFF; width:50%; border: solid black 2px; padding: 25px; padding-top: 10px; padding-bottom: 10px; border-radius: 8px; margin-left: 10px; margin-top: 10px;">
<span><a href="http://agency-software.org/" target="_blank"><img src="http://agency-software.org/agency_logo_medium.png"/></a></span>
<span style="font-size: 150%; font-weight: bold; vertical-align: middle; ">Password Reset</span>
</div>
<h1><a href="$reset_password_url">Click here</a> to reset your AGENCY Password</h1>
<div style="background: #EEEEFF; border-color: #000000; padding: 10;">
This email was generated by AGENCY.<br />
You cannot reply to this email.<br />
</div>
</body></html>'
);

