CREATE VIEW client AS
SELECT 
	tbl_client.client_id, 
	COALESCE(prot.name_last, tbl_client.name_last) AS name_last, 
	COALESCE(prot.name_first, tbl_client.name_first) AS name_first,
	COALESCE(prot.name_middle, tbl_client.name_middle) AS name_middle,
	CASE WHEN (prot.client_protected_id IS NOT NULL) THEN NULL::character varying ELSE tbl_client.name_suffix END AS name_suffix,
	COALESCE(prot.name_alias, tbl_client.name_alias) AS name_alias,
	COALESCE(prot.dob, tbl_client.dob) AS dob,
	COALESCE(prot.ssn, tbl_client.ssn) AS ssn,
	tbl_client.gender_code,
	tbl_client.pronoun_subject,
	tbl_client.pronoun_object,
	tbl_client.pronoun_possessive,
	tbl_client.pronoun_possessive_pronoun,
	tbl_client.pronoun_reflexive,
	tbl_client.hispanic_origin_code,
	tbl_client.needs_interpreter_code,
	tbl_client.language_code,
	tbl_client.veteran_status_code,
	tbl_client.sexual_minority_status_code,
	tbl_client.clinical_id,
	tbl_client.king_cty_id,
	tbl_client.spc_id,
	tbl_client.comments,
	tbl_client.med_issues,
	tbl_client.medications,
	tbl_client.med_allergies,
	tbl_client.last_photo_at,
	tbl_client.issue_no,
	tbl_client.resident_id,
	tbl_client.added_at,
	tbl_client.added_by,
	tbl_client.changed_at,
	tbl_client.changed_by,
	tbl_client.is_deleted,
	tbl_client.deleted_at,
	tbl_client.deleted_by,
	tbl_client.deleted_comment,
	tbl_client.sys_log,
	(((((COALESCE(prot.name_last, tbl_client.name_last))::text || ', '::text) || (COALESCE(prot.name_first, tbl_client.name_first))::text) || COALESCE((' '::text || (prot.name_middle)::text), (' '::text || (tbl_client.name_middle)::text), ''::text)) || COALESCE((', '::text || (CASE WHEN (prot.client_protected_id IS NULL) THEN tbl_client.name_suffix ELSE NULL::character varying END)::text), ''::text)) AS name_full,
	((((((COALESCE(prot.name_last, tbl_client.name_last))::text || ', '::text) || (COALESCE(prot.name_first, tbl_client.name_first))::text) || COALESCE((' '::text || (prot.name_middle)::text), (' '::text || (tbl_client.name_middle)::text), ''::text)) || COALESCE((', '::text || (CASE WHEN (prot.client_protected_id IS NULL) THEN tbl_client.name_suffix ELSE NULL::character varying END)::text), ''::text)) || COALESCE((' '::text || (prot.name_alias)::text), (' '::text || (tbl_client.name_alias)::text), ''::text)) AS name_full_alias,
	CASE WHEN (prot.client_protected_id IS NOT NULL) THEN true ELSE false END AS is_protected_id 
FROM tbl_client 
	LEFT JOIN client_protected_current prot USING (client_id)
WHERE (NOT tbl_client.is_deleted);

