INSERT INTO tbl_l_bar_reason VALUES ('AS','Assault on Staff','ASSAULTIVE',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('AC','Assault on Client','ASSAULTIVE',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('DV','Domestic Violence','ASSAULTIVE',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('FT','Fighting','ASSAULTIVE',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('MC','Menacing Client','ASSAULTIVE',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('MS','Menacing Staff','ASSAULTIVE',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('CR','Crack in Agency','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('CT','Criminal Trespass','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('EM','Exchanging Money','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('IE','Illegal Entry','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('PD','Property Destruction','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('SPD','Seattle Police Dept','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('TC','Threatening Client','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('TH','Theft','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('TS','Threatening Staff','AUTO_BRC',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('ETOH','Under Influence','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('NC','Non-Cooperation','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('PB','Prior BRC','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('PO','Poss Drugs, Alc, Equip','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('RA','Respite Abuse','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('RD','Redeeming','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('RL','Racist Language','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('SIB','Sexually Inappropriate Behavior','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('SM','Smoking','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('VA','Verbally Abusive','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
INSERT INTO tbl_l_bar_reason VALUES ('WN','Weapons','1_OR_3_DAY',sys_user(),current_timestamp,sys_user(),current_timestamp);
